### ISSUE TITLE
Package unavailble

### ISSUE THREAD

**Issue by koresar** [Offirmo/traffic-lights-simulator#1]
The package seems private:
`npm i -S @offirmo/traffic-lights-controller`
reports 404 Not Found.

Please run `npm access public` or `npm publish` if it was not published. Thanks 👍

**Comment by Offirmo** [comment]
@koresar Sorry, I didn't really publish this exercise to not pollute the npm repo ^^

But if I had published it, it would have worked like that.

I suggest to install it directly from GitHub: `npm i Offirmo/traffic-lights-simulator`

The calling code becomes:
```javascript
const TrafficLightsController = require('traffic-lights-simulator')

const controller = TrafficLightsController.factory({
	onStateChange: console.log  // or whatever
})
```

**Comment by Offirmo** [comment]
Updated the README

**Comment by Offirmo** [comment]
Shouldn't we be sleeping? ^^

**Comment by koresar** [comment]
Thank you. 👍
